### ISSUE TITLE
Cant see a map

### ISSUE THREAD

**Issue by Tealk144** [JonahAragon/PoGoMapWiki#7]
I get this error can you help me? 

Hoppla! Ein Fehler ist aufgetreten.
Google Maps wurde auf dieser Seite nicht richtig geladen. Technische Details dazu entnimmst du der JavaScript-Konsole.

**Comment by andreblue** [comment]
Check your javascript console and is this happening on the wiki or the program the map?
If it is with the map go https://github.com/AHAAAAAAA/PokemonGo-Map and create an issue there instead of here. This is for the wiki

**Comment by Tealk144** [comment]
oh ok thanks, but where i find the javascript console?

**Comment by andreblue** [comment]
Right click on the page, and you have inspect element in chrome, and click on console
for firefox do Ctrl + Shift + K

**Comment by JonahAragon** [comment]
This should be moved to the other repo :)
